---
title: "Working with images for html files"
output: html_notebook
---

Working with images and generating web content from different image types and sizes has been a challenging aspect of working with this sort of website generation.

I found myself saying too many times that I hate working with images in websites before I could check myself. This seems to make it obvious to me that I need to get this "down-pac" as soon as possible. Here are my notes in another attempt to do so....

Image size, projection dimensions, and printing dimensions all seem to change differently at different times when working with these different image types. To break this down I have divided the different aspects and rules under each of the different content types available in RStudio using packages like `rmarkdown` and `bookdown`.

## Web images

Currently I am working in a dynamic HTML5 template and rendering different aspects of the original template into RMarkdown workflow for html_documents. As I have little background in such matters before now I have tried to work with existing packages and framework I manage to find in the open source community.

### Logos and avatars



## Glossary of terms

### Size: 

### Pixels

### Scale

## Web apps/software



## Other software





## R packages

ImageMagic is accessed through a package called `imageMagic`. Working 

```{r}
# install
# library(imag)
```

